-- create sequence hibernate_sequence start with 1 increment by 1;
-- create sequence client_sequence start with 1 increment by 1;
-- create sequence address_sequence start with 1 increment by 1;
-- create sequence phone_sequence start with 1 increment by 1;

create table address
(
    id int8 generated by default as identity,
     street varchar(255),
      client_id int8,
      primary key (id)
);
create table client
(
    id int8 generated by default as identity,
     name varchar(255),
       primary key (id)
);
create table phone
(
    id int8 generated by default as identity,
     number varchar(255),
      client_id int8,
       primary key (id)
);


-- alter table if exists clientOld add constraint FKb137u2cl2ec0otae32lk5pcl2 foreign key (address_id) references address;
-- alter table if exists phone add constraint FK3o48ec26lujl3kf01hwqplhn2 foreign key (client_id) references clientOld;

-- insert into client (name, id) values ('Ilya', 1);
-- insert into client (name, id) values ('Kolya', 2);
--
-- insert into address (street, client_id) values ('Matrosova', 1);
-- insert into address (street, client_id) values ('Bogoslovskaya', 2);
--
-- insert into phone (client_id, number) values (1, 123);
-- insert into phone (client_id, number) values (1, 1234);
-- insert into phone (client_id, number) values (2, 234);
-- insert into phone (client_id, number) values (2, 2345);

alter table address add foreign key (client_id) references client(id);
alter table phone add foreign key (client_id) references client(id);